name: Deploy to Azure App Service

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # Cancel any running deployments

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Clean install dependencies
      run: |
        rm -rf node_modules
        rm -f package-lock.json
        npm install --no-audit --no-optional
        npm install express-session@1.17.3 passport@0.6.0 passport-azure-ad@4.3.5

    - name: Build
      env:
        NODE_ENV: production
        SKIP_LINT: true  # Skip linting during build
      run: |
        npm run build

    - name: Prepare deployment package
      run: |
        # Create deployment config
        echo "[config]
        SCM_DO_BUILD_DURING_DEPLOYMENT=false" > .deployment

        # Create a clean deployment package
        mkdir deploy
        cp -r dist server node_modules package.json .deployment deploy/
        cd deploy
        zip -r ../package.zip .

    - name: Deploy to Azure App Service
      id: deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: uptime-kuma-version-three
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: package.zip
        clean: true  # Enable clean deployment

    # Set app settings after deployment
    - name: Update App Settings
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config appsettings set --name uptime-kuma-version-three --resource-group TestRG --settings STARTUP_COMMAND="node server/server.js" NODE_ENV="production" WEBSITES_PORT="3001" AZURE_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}" AZURE_TENANT_ID="${{ secrets.AZURE_TENANT_ID }}" SCM_DO_BUILD_DURING_DEPLOYMENT="false"

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}