name: Deploy to Azure App Service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Clean install dependencies
      run: |
        rm -rf node_modules
        rm -f package-lock.json
        npm install
        npm install express-session@1.17.3 passport@0.6.0 passport-azure-ad@4.3.5

    - name: Build
      run: |
        npm run build

    - name: Create deployment config files
      run: |
        echo "[config]
        SCM_DO_BUILD_DURING_DEPLOYMENT=false" > .deployment
        
        echo "node_modules/
        .git/
        .github/
        .vscode/
        test/
        extra/
        docker/
        config/
        .env
        .gitignore
        README.md" > .deployignore

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: uptime-kuma-version-three
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
        app-settings-json: |
          {
            "STARTUP_COMMAND": "node server/server.js",
            "NODE_ENV": "production",
            "WEBSITES_PORT": "3001",
            "AZURE_CLIENT_ID": "${{ secrets.AZURE_CLIENT_ID }}",
            "AZURE_TENANT_ID": "${{ secrets.AZURE_TENANT_ID }}"
          }

    - name: Post deployment script
      run: |
        echo "Deployment completed, waiting for app to start..."
        sleep 30

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}