name: Deploy to Azure App Service

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Increased timeout for stability

    strategy:
      matrix:
        node-version: [20]
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm install express-session@1.17.3 passport@0.6.0 passport-azure-ad@4.3.5

    - name: Build
      env:
        NODE_ENV: production
        SKIP_LINT: true
      run: |
        npm run build

    - name: Prepare deployment package
      run: |
        mkdir deploy
        cp -r dist server node_modules package.json deploy/
        cd deploy
        zip -r ../package.zip .

    - name: Deploy to Azure App Service
      id: deploy
      uses: azure/webapps-deploy@v4
      with:
        app-name: uptime-kuma-version-three
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: package.zip
        clean: true  # Forces a clean deployment

    - name: Restart App Service (Fix Stuck State)
      run: |
        az webapp restart --name uptime-kuma-version-three --resource-group TestRG

    - name: Update App Settings
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config appsettings set --name uptime-kuma-version-three --resource-group TestRG --settings STARTUP_COMMAND="node server/server.js" NODE_ENV="production" WEBSITES_PORT="3001" AZURE_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}" AZURE_TENANT_ID="${{ secrets.AZURE_TENANT_ID }}" SCM_DO_BUILD_DURING_DEPLOYMENT="false"

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
