name: Deploy to Azure App Service

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history and tags

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Install dependencies and build
    - name: Install dependencies and build
      run: |
        npm install -g vite
        npm ci --legacy-peer-deps
        npm run build
        npm run download-dist

    # Create .deployment file
    - name: Create .deployment file
      run: |
        echo "[config]
        SCM_DO_BUILD_DURING_DEPLOYMENT=false" > .deployment

    # Create .gitignore for deployment
    - name: Create deployment ignore file
      run: |
        echo "node_modules/
        .git/
        .github/
        .vscode/
        test/
        extra/
        docker/
        config/
        .env
        .gitignore
        README.md" > .deployignore

    # Create web.config for Azure
    - name: Create web.config
      run: |
        echo '<?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <system.webServer>
            <handlers>
              <add name="iisnode" path="server/server.js" verb="*" modules="iisnode"/>
            </handlers>
            <rewrite>
              <rules>
                <rule name="DynamicContent">
                  <conditions>
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
                  </conditions>
                  <action type="Rewrite" url="server/server.js"/>
                </rule>
              </rules>
            </rewrite>
            <iisnode node_env="production" nodeProcessCommandLine="node"/>
          </system.webServer>
        </configuration>' > web.config

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'uptime-kuma-version-three'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: . 